#!/usr/bin/env python3
"""Skill-orchestration generator (EXEC-431).

Single source of truth = the `lifecycle:` block in each skill's SKILL.md
frontmatter. This script reads every skill under meta/.claude/skills/ and
generates two artifacts (never hand-maintained):

  - skill-orchestration.yaml  : machine-readable registry (drives the SessionStart hook)
  - WORKFLOW.md               : human-readable end-to-end workflow doc

Stdlib-only (no pyyaml) so it runs anywhere with python3, Claude-independent.

Usage:
  gen_orchestration.py            # regenerate both artifacts
  gen_orchestration.py --check    # exit 1 if committed artifacts are stale (for CI)
"""
from __future__ import annotations
import sys, re, os
from pathlib import Path

PHASES = ["session-start", "project-start", "execution-loop", "work-close", "on-trigger"]
CADENCES = ["once-per-session", "once-per-project", "loop-until-done", "on-demand"]
PHASE_TITLES = {
    "session-start": "Session start — orient before any work",
    "project-start": "Project start — frame & structure a new initiative",
    "execution-loop": "Execution loop — repeat until the unit of work closes",
    "work-close": "Work close — QA, simplify, and ship",
    "on-trigger": "On trigger — fired on demand by keyword/event",
}
DEFAULT = {"phase": "on-trigger", "cadence": "on-demand", "trigger": "", "classified": False}

HERE = Path(__file__).resolve().parent
SKILLS_DIR = HERE.parent / ".claude" / "skills"


def parse_frontmatter(text: str) -> dict:
    """Extract the YAML frontmatter (between the first two '---') as a shallow dict,
    with one level of nesting supported for the `lifecycle:` block."""
    m = re.match(r"^---\n(.*?)\n---", text, re.DOTALL)
    if not m:
        return {}
    body = m.group(1)
    top: dict = {}
    cur_block = None
    for raw in body.splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        indented = raw[0] in " \t"
        line = raw.strip()
        if indented and cur_block is not None:
            if ":" in line:
                k, _, v = line.partition(":")
                top[cur_block][k.strip()] = _scalar(v.strip())
            continue
        # top-level key
        k, _, v = line.partition(":")
        k = k.strip()
        v = v.strip()
        if v == "":
            top[k] = {}
            cur_block = k
        else:
            top[k] = _scalar(v)
            cur_block = None
    return top


def _scalar(v: str):
    if len(v) >= 2 and v[0] in "\"'" and v[-1] == v[0]:
        return v[1:-1]
    return v


def load_skills() -> list[dict]:
    skills = []
    for skill_md in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        fm = parse_frontmatter(skill_md.read_text())
        name = fm.get("name") or skill_md.parent.name
        lc = fm.get("lifecycle") if isinstance(fm.get("lifecycle"), dict) else {}
        entry = {
            "name": name,
            "phase": lc.get("phase", DEFAULT["phase"]),
            "cadence": lc.get("cadence", DEFAULT["cadence"]),
            "trigger": lc.get("trigger", (fm.get("description", "") or "")[:120]),
            "classified": bool(lc),
        }
        skills.append(entry)
    return skills


def validate(skills: list[dict]) -> list[str]:
    errs = []
    for s in skills:
        if s["phase"] not in PHASES:
            errs.append(f"{s['name']}: invalid phase {s['phase']!r}")
        if s["cadence"] not in CADENCES:
            errs.append(f"{s['name']}: invalid cadence {s['cadence']!r}")
    return errs


def _q(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_yaml(skills: list[dict]) -> str:
    out = [
        "# GENERATED by meta/orchestration/gen_orchestration.py — do not edit by hand.",
        "# Source of truth: the `lifecycle:` block in each skill's SKILL.md frontmatter.",
        "version: 1",
        "phases: [" + ", ".join(PHASES) + "]",
        "cadences: [" + ", ".join(CADENCES) + "]",
        "skills:",
    ]
    # stable order: by phase order, then name
    skills = sorted(skills, key=lambda s: (PHASES.index(s["phase"]), s["name"]))
    for s in skills:
        out += [
            f"  - name: {s['name']}",
            f"    phase: {s['phase']}",
            f"    cadence: {s['cadence']}",
            f"    trigger: {_q(s['trigger'])}",
            f"    classified: {'true' if s['classified'] else 'false'}",
        ]
    return "\n".join(out) + "\n"


def render_workflow(skills: list[dict]) -> str:
    out = [
        "<!-- GENERATED by meta/orchestration/gen_orchestration.py — do not edit by hand. -->",
        "# Skill lifecycle & end-to-end workflow",
        "",
        "How the skills are invoked across the work lifecycle. Source of truth is the",
        "`lifecycle:` frontmatter in each `SKILL.md`; regenerate with",
        "`python3 meta/orchestration/gen_orchestration.py`.",
        "",
        "Phases run in order: **session-start → project-start → execution-loop → work-close**,",
        "with **on-trigger** skills firing on demand throughout.",
        "",
    ]
    for phase in PHASES:
        members = [s for s in skills if s["phase"] == phase]
        if not members:
            continue
        out += [f"## {PHASE_TITLES[phase]}", "", "| Skill | Cadence | Trigger |", "| --- | --- | --- |"]
        for s in sorted(members, key=lambda s: s["name"]):
            unclass = "" if s["classified"] else " _(unclassified — defaulted)_"
            out.append(f"| `{s['name']}`{unclass} | {s['cadence']} | {s['trigger']} |")
        out.append("")
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    skills = load_skills()
    errs = validate(skills)
    if errs:
        print("VALIDATION FAILED:\n  " + "\n  ".join(errs), file=sys.stderr)
        return 2
    yaml_path = HERE / "skill-orchestration.yaml"
    wf_path = HERE / "WORKFLOW.md"
    yaml_txt, wf_txt = render_yaml(skills), render_workflow(skills)
    if "--check" in argv:
        stale = []
        for p, txt in [(yaml_path, yaml_txt), (wf_path, wf_txt)]:
            if not p.exists() or p.read_text() != txt:
                stale.append(p.name)
        if stale:
            print(f"STALE (regenerate): {', '.join(stale)}", file=sys.stderr)
            return 1
        print("orchestration artifacts up to date")
        return 0
    yaml_path.write_text(yaml_txt)
    wf_path.write_text(wf_txt)
    n = sum(1 for s in skills if s["classified"])
    print(f"wrote {yaml_path.name} + {wf_path.name} ({n}/{len(skills)} skills classified)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
